name: Mirror to Gitea
on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://git.cuqmbr.xyz/cuqmbr/KeepItUp.git'
            GIT_USERNAME: cuqmbr
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
